{% set name = "facebook_business" %}
{% set version = "15.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/facebook_business-{{ version }}.tar.gz
  sha256: a814df038fed04d7a470e2240cbaac70e62c9181b3603154024cffd83955a255

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - curlify >=2.1.0
    - enum34
    - pycountry >=19.8.18
    - python >=3.6
    - requests >=2.3.0
    - six >=1.7.3

test:
  imports:
    - facebook_business
    - facebook_business.adobjects
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/facebook-python-business-sdk
  summary: Facebook Business SDK
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kcemenike
