{% set name = "facebook_business" %}
{% set version = "24.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/facebook_business-{{ version }}.tar.gz
  sha256: 1c93e8e198ec1c2d42e957db2304ba0348f061c0bfe27bac00bfb576a9b4ea00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.3.0
    - six >=1.7.3
    - curlify >=2.1.0
    - pycountry >=19.8.18
    - aiohttp

test:
  imports:
    - facebook_business
    - facebook_business.adobjects
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/facebook/facebook-python-business-sdk
  summary: Facebook Business SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebook/facebook-python-business-sdk
  doc_url: https://developers.facebook.com/docs/business-sdk

extra:
  recipe-maintainers:
    - kcemenike
    - xylar
