schema_version: 1

context:
  name: facebook_business
  version: 25.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/facebook_business-${{ version }}.tar.gz
  sha256: 60f866c63c56efa2eb247c1fbba1d90bb64ee2ccd356242bc6271ead36a425d7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests >=2.3.0
    - six >=1.7.3
    - curlify >=2.1.0
    - pycountry >=19.8.18
    - aiohttp
    - capi-param-builder-python >=1.3.0
tests:
  - python:
      imports:
        - facebook_business
        - facebook_business.adobjects
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Facebook Business SDK
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/facebook/facebook-python-business-sdk
  repository: https://github.com/facebook/facebook-python-business-sdk
  documentation: https://developers.facebook.com/docs/business-sdk

extra:
  recipe-maintainers:
    - kcemenike
    - xylar
